### ISSUE TITLE
Ethernet not working

### ISSUE THREAD

**Issue by TanweerJugoo** [ARGAMX/Hackintosh-Intel-i9-10850k-MSI-Z490-GAMING-EDGE-WIFI#10]
Hello i have used your EFi in my build on changing a few things in the config.plist file. unfortunately i am unable to get ethernet for install. Can you please help me. Thank you.

**Comment by ARGAMX** [comment]
@TanweerJugoo hi

Network works fine for me on this config.
In your situation I can only suggest you to
go through OpenCore-Install-Guide and generate your own config.plist 

https://dortania.github.io/OpenCore-Install-Guide/

**Comment by TanweerJugoo** [comment]
Oh sorry i fixed i need to delete this issue.
